name: Demo workflow
on: workflow_dispatch
jobs:
  print_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: echo Guthub action!
      - name: Print a few lines
        run: |
          echo first line
          echo second line
          echo third line
